# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: codelens/v1/analysis.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import codelens.v1.analysis_pb2 as codelens_dot_v1_dot_analysis__pb2


class AnalysisService(Protocol):
    async def analyze(self, request: codelens_dot_v1_dot_analysis__pb2.AnalyzeRequest, ctx: RequestContext) -> codelens_dot_v1_dot_analysis__pb2.AnalyzeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def analyze_stream(self, request: codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamRequest, ctx: RequestContext) -> AsyncIterator[codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_analysis(self, request: codelens_dot_v1_dot_analysis__pb2.GetAnalysisRequest, ctx: RequestContext) -> codelens_dot_v1_dot_analysis__pb2.GetAnalysisResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_file_source(self, request: codelens_dot_v1_dot_analysis__pb2.GetFileSourceRequest, ctx: RequestContext) -> codelens_dot_v1_dot_analysis__pb2.GetFileSourceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_repos(self, request: codelens_dot_v1_dot_analysis__pb2.ListReposRequest, ctx: RequestContext) -> codelens_dot_v1_dot_analysis__pb2.ListReposResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_repo(self, request: codelens_dot_v1_dot_analysis__pb2.DeleteRepoRequest, ctx: RequestContext) -> codelens_dot_v1_dot_analysis__pb2.DeleteRepoResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AnalysisServiceASGIApplication(ConnectASGIApplication[AnalysisService]):
    def __init__(self, service: AnalysisService | AsyncGenerator[AnalysisService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/codelens.v1.AnalysisService/Analyze": Endpoint.unary(
                    method=MethodInfo(
                        name="Analyze",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.AnalyzeRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.AnalyzeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.analyze,
                ),
                "/codelens.v1.AnalysisService/AnalyzeStream": Endpoint.server_stream(
                    method=MethodInfo(
                        name="AnalyzeStream",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.analyze_stream,
                ),
                "/codelens.v1.AnalysisService/GetAnalysis": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAnalysis",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.GetAnalysisRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.GetAnalysisResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_analysis,
                ),
                "/codelens.v1.AnalysisService/GetFileSource": Endpoint.unary(
                    method=MethodInfo(
                        name="GetFileSource",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.GetFileSourceRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.GetFileSourceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_file_source,
                ),
                "/codelens.v1.AnalysisService/ListRepos": Endpoint.unary(
                    method=MethodInfo(
                        name="ListRepos",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.ListReposRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.ListReposResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_repos,
                ),
                "/codelens.v1.AnalysisService/DeleteRepo": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteRepo",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.DeleteRepoRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.DeleteRepoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_repo,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codelens.v1.AnalysisService"


class AnalysisServiceClient(ConnectClient):
    async def analyze(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.AnalyzeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codelens_dot_v1_dot_analysis__pb2.AnalyzeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Analyze",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.AnalyzeRequest,
                output=codelens_dot_v1_dot_analysis__pb2.AnalyzeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def analyze_stream(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="AnalyzeStream",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamRequest,
                output=codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_analysis(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.GetAnalysisRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codelens_dot_v1_dot_analysis__pb2.GetAnalysisResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAnalysis",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.GetAnalysisRequest,
                output=codelens_dot_v1_dot_analysis__pb2.GetAnalysisResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_file_source(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.GetFileSourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codelens_dot_v1_dot_analysis__pb2.GetFileSourceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetFileSource",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.GetFileSourceRequest,
                output=codelens_dot_v1_dot_analysis__pb2.GetFileSourceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_repos(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.ListReposRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codelens_dot_v1_dot_analysis__pb2.ListReposResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRepos",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.ListReposRequest,
                output=codelens_dot_v1_dot_analysis__pb2.ListReposResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_repo(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.DeleteRepoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codelens_dot_v1_dot_analysis__pb2.DeleteRepoResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteRepo",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.DeleteRepoRequest,
                output=codelens_dot_v1_dot_analysis__pb2.DeleteRepoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class AnalysisServiceSync(Protocol):
    def analyze(self, request: codelens_dot_v1_dot_analysis__pb2.AnalyzeRequest, ctx: RequestContext) -> codelens_dot_v1_dot_analysis__pb2.AnalyzeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def analyze_stream(self, request: codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamRequest, ctx: RequestContext) -> Iterator[codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_analysis(self, request: codelens_dot_v1_dot_analysis__pb2.GetAnalysisRequest, ctx: RequestContext) -> codelens_dot_v1_dot_analysis__pb2.GetAnalysisResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_file_source(self, request: codelens_dot_v1_dot_analysis__pb2.GetFileSourceRequest, ctx: RequestContext) -> codelens_dot_v1_dot_analysis__pb2.GetFileSourceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_repos(self, request: codelens_dot_v1_dot_analysis__pb2.ListReposRequest, ctx: RequestContext) -> codelens_dot_v1_dot_analysis__pb2.ListReposResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_repo(self, request: codelens_dot_v1_dot_analysis__pb2.DeleteRepoRequest, ctx: RequestContext) -> codelens_dot_v1_dot_analysis__pb2.DeleteRepoResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AnalysisServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AnalysisServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/codelens.v1.AnalysisService/Analyze": EndpointSync.unary(
                    method=MethodInfo(
                        name="Analyze",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.AnalyzeRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.AnalyzeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.analyze,
                ),
                "/codelens.v1.AnalysisService/AnalyzeStream": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="AnalyzeStream",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.analyze_stream,
                ),
                "/codelens.v1.AnalysisService/GetAnalysis": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAnalysis",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.GetAnalysisRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.GetAnalysisResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_analysis,
                ),
                "/codelens.v1.AnalysisService/GetFileSource": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetFileSource",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.GetFileSourceRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.GetFileSourceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_file_source,
                ),
                "/codelens.v1.AnalysisService/ListRepos": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListRepos",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.ListReposRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.ListReposResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_repos,
                ),
                "/codelens.v1.AnalysisService/DeleteRepo": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteRepo",
                        service_name="codelens.v1.AnalysisService",
                        input=codelens_dot_v1_dot_analysis__pb2.DeleteRepoRequest,
                        output=codelens_dot_v1_dot_analysis__pb2.DeleteRepoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_repo,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/codelens.v1.AnalysisService"


class AnalysisServiceClientSync(ConnectClientSync):
    def analyze(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.AnalyzeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codelens_dot_v1_dot_analysis__pb2.AnalyzeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Analyze",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.AnalyzeRequest,
                output=codelens_dot_v1_dot_analysis__pb2.AnalyzeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def analyze_stream(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="AnalyzeStream",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamRequest,
                output=codelens_dot_v1_dot_analysis__pb2.AnalyzeStreamResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_analysis(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.GetAnalysisRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codelens_dot_v1_dot_analysis__pb2.GetAnalysisResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAnalysis",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.GetAnalysisRequest,
                output=codelens_dot_v1_dot_analysis__pb2.GetAnalysisResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_file_source(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.GetFileSourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codelens_dot_v1_dot_analysis__pb2.GetFileSourceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetFileSource",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.GetFileSourceRequest,
                output=codelens_dot_v1_dot_analysis__pb2.GetFileSourceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_repos(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.ListReposRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codelens_dot_v1_dot_analysis__pb2.ListReposResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRepos",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.ListReposRequest,
                output=codelens_dot_v1_dot_analysis__pb2.ListReposResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_repo(
        self,
        request: codelens_dot_v1_dot_analysis__pb2.DeleteRepoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> codelens_dot_v1_dot_analysis__pb2.DeleteRepoResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteRepo",
                service_name="codelens.v1.AnalysisService",
                input=codelens_dot_v1_dot_analysis__pb2.DeleteRepoRequest,
                output=codelens_dot_v1_dot_analysis__pb2.DeleteRepoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
